name: Build and deploy React app to Azure Web App - RFQ-Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Package ONLY the contents of build/ (so they land at /home/site/wwwroot)
      - name: Prepare deployable artifact (wwwroot contents)
        run: |
          rm -rf artifact
          mkdir -p artifact
          cp -r build/* artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: artifact
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rfq-management'
          slot-name: 'Production'
          package: artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FF8D0A0E8CC446A18C4CA9176671B031 }}
          startup-command: >
            npx http-server /home/site/wwwroot -p ${PORT:-8080} --proxy http://localhost:${PORT:-8080}?
